name: CI Tests

on:
  pull_request:
  push:
    branches:
      - master
      - v*

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        stability: [prefer-stable]
        versions: [
          { php: 8.1, phpunit: 10 }, { php: 8.2, phpunit: 10 }, { php: 8.3, phpunit: 10 },
          { php: 8.2, phpunit: 11 }, { php: 8.3, phpunit: 11 }
        ]

    name: PHP ${{ matrix.versions.php }} - PHPUnit ${{ matrix.versions.phpunit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.versions.php }}
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "phpunit/phpunit=^${{ matrix.versions.phpunit }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run phpunit tests
        run: composer test
        
      - name: Run Coveralls
        if: matrix.php == '8.3'
        run: |
          composer global require --ansi php-coveralls/php-coveralls:^2.7
          php-coveralls --coverage_clover=build/logs/clover.xml -v
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: PHP ${{ matrix.php-versions }}
  coveralls-finish:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
          fail-on-error: false
